const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.resolve(__dirname, '../.env') });

const envFilePath = path.resolve(__dirname, '../src/environments/environment.ts');
const apiUrl = process.env.API_URL || '';

const fileContent = `// This file is auto-generated by scripts/generate-env.js
export const environment = {
  production: false,
  apiUrl: '${apiUrl}'
};
`;

fs.mkdirSync(path.dirname(envFilePath), { recursive: true });
fs.writeFileSync(envFilePath, fileContent);
console.log(`Generated ${envFilePath}`);
fs.writeFileSync(
  path.resolve(__dirname, '../src/environments/environment.prod.ts'),
  envFileContent
);
