const fs = require('fs');
const path = require('path');
const dotenvPath = path.resolve(__dirname, '../.env');
let apiUrl = '';

if (fs.existsSync(dotenvPath)) {
  require('dotenv').config({ path: dotenvPath });
  apiUrl = process.env.API_URL || '';
} else {
  console.warn('.env file not found. apiUrl will be empty.');
}

const envDir = path.resolve(__dirname, '../src/environments');
const envFilePath = path.join(envDir, 'environment.ts');

const fileContent = `// This file is auto-generated by scripts/generate-env.js
export const environment = {
  production: false,
  apiUrl: '${apiUrl}'
};
`;

fs.mkdirSync(envDir, { recursive: true });
fs.writeFileSync(envFilePath, fileContent);
console.log(`Generated ${envFilePath}`);
fs.writeFileSync(
  path.resolve(__dirname, '../src/environments/environment.prod.ts'),
  fileContent
);
